title: OPM lab
description: The code used for data collection and data analysis of OPM data
theme: just-the-docs

url: https://laurabpaulsen.github.io/OPM_lab/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
